title: Workshop on Toxicity Detection in Games
description: Toxicity Dual Detection workshop at The Web Conference (WWW) aims to promote research on toxicity dual detection using CONDA, a CONtextual Dual-Annotated dataset for in-game toxicity understanding and detection.
show_downloads: true

#theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
